# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  sonarqube:
    image: sonarqube:9.9.5-community
    restart: always
    ports:
      - "9000:9000"